@startuml
class InventoryApp{
    main()
    start()
}
class FileHandler{

    +saveTSV()
    +saveHTML()
    +saveJSON()

    +loadTSV()
    +loadHTML()
    +loadJSON()

    +readLines()
}
class InventoryMainController{
    +initialize()

    +addItem()
    +deleteClicked
    +deleteListItem

    +configureFileChooser()

    +saveInventoryListClick()
    +saveInventoryList()

    +loadListClick()
    +loadList()
    +makeFilteredList

}
class Item{
    -SimpleStringProperty price
    -SimpleStringProperty name
    -SimpleStringProperty serialNumber
    -LinkedList<String> listSerialNumbers

    +priceProperty()
    +productNameProperty()
    +serialNumberProperty()

    +setPrice()
    +setSerialNumber()
    +setProductName()

    +equals()    @Override
    +hashcode()     @Override

}
InventoryApp -- InventoryMainController
InventoryMainController -- FileHandler
InventoryMainController -- Item
FileHandler -- Item
@enduml